version: "3.0"

services:
  database:
    container_name: database
    image: mysql:latest
    volumes:
      - ./mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --explicit_defaults_for_timestamp
    environment:
      MYSQL_DATABASE: "onlineshop"
      MYSQL_ROOT_PASSWORD: "123"
    ports:
      - "3306:3306"
    networks:
      - spring-network

  app:
    container_name: "spring"
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/onlineshop
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - spring-network

networks:
  spring-network:
    driver: bridge
